apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "fullname" . }}
spec:
  ports:
  - port: 45454
    name: server
  - port: 8042
    name: webui-address
  - port: 15551
    name: llap-shuffle
  - port: 15002
    name: llap-daemon
  - port: 15003
    name: llap-rpc
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
