kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "fullname" . }}
spec:
  ports:
  - port: 10000
    name: server
  - port: 10002
    name: webui-address
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
