# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: dockerbarbarians

zookeeper:
  image: zookeeper:0.1.0
  count: 5
  cpu: 0.5
  mem: 2Gi
  ps_mem: 1g

  log_level: INFO

service:
  name: zk-serv
