# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

hive-hs2:
  image: hive
  count: 1
  llapd_count: 4
  ps_mem: 8g
  mem: 8Gi
  cpu: 1
  llapd_mem: 24g

  log_level: INFO

service:
  name: hs2-serv

