dependencies:
  - name: zookeeper
    repository: https://charts.barbarians.io/zookeeper
    version: 0.1.0-badh0.1.0
  - name: yarn-rm
    repository: https://charts.barbarians.io/yarn-rm
    version: 0.1.0-badh0.1.0
