apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-hadoop-conf
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  yarn-site.xml: |-
{{ tpl (.Files.Get "files/hadoop/yarn-site.xml") . | indent 4 }}
  core-site.xml: |-
{{ tpl (.Files.Get "files/hadoop/core-site.xml") . | indent 4 }}
  mapred-site.xml: |-
{{ tpl (.Files.Get "files/hadoop/mapred-site.xml") . | indent 4 }}
  hdfs-site.xml: |-
{{ tpl (.Files.Get "files/hadoop/hdfs-site.xml") . | indent 4 }}
  log4j.properties: |-
{{ tpl (.Files.Get "files/hadoop/log4j.properties") . | indent 4 }}
