apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.hive_hs2.count }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        name: {{ template "fullname" . }}
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "{{ .Values.hive_hs2.mem }}"
            cpu: "{{ .Values.hive_hs2.cpu }}"
        volumeMounts:
        - mountPath: /opt/barbarian/hadoop/etc/hadoop
          name: yarn-cfg-volume
        - name: hive-cfg-volume
          mountPath: /opt/barbarian/hive/conf
        - name: tez-cfg-volume
          mountPath: /opt/barbarian/tez/conf
        - name: slider-cfg-volume
          mountPath: /opt/barbarian/slider/conf
        ports:
        - containerPort: 10000
          name: server
        - containerPort: 10002
          name: webui-address
        command:
        - sh
        - -c
        - "/opt/barbarian/control/start-hiveserver2 \
          --zk_connect={{ .Values.zookeeper.service.name }} \
          --rm_connect={{ .Values.yarn_rm.service.name }} \
          --igfs_connect={{ .Values.ignite.service.name }} \
          --hms_connect={{ .Values.hive_hms.service.name }}:9083"
      initContainers:
      - name: start-hive-llap
        image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        command:
        - sh
        - -c 
        - "HADOOP_CLASSPATH=/opt/barbarian/hadoop/etc/hadoop:/opt/barbarian/hadoop/share/hadoop/yarn/*:/opt/barbarian/hadoop/share/hadoop/yarn/lib/*:/opt/barbarian/tez/conf \
          /opt/barbarian/control/start-llap \
          --zk_connect={{ .Values.zookeeper.service.name }} \
          --rm_connect={{ .Values.yarn_rm.service.name }} \
          --igfs_connect={{ .Values.ignite.service.name }} \
          --hms_connect={{ .Values.hive_hms.service.name }}:9083 \
          --llapd_count={{ .Values.hive_hs2.llapd_count }} \
          --llapd_ram={{ .Values.hive_hs2.llapd_mem }}"
        volumeMounts:
        - name: hive-cfg-volume
          mountPath: "/opt/barbarian/hive/conf"
        - name: tez-cfg-volume
          mountPath: "/opt/barbarian/tez/conf"
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
        - name: slider-cfg-volume
          mountPath: "/opt/barbarian/slider/conf"
      - name: await-llap
        image: {{ .Values.global.repo }}/{{ .Values.hive_hs2.image }}
        command:
        - sh
        - -c 
        - "/opt/barbarian/control/await-llap"
        volumeMounts:
        - name: yarn-cfg-volume
          mountPath: "/opt/barbarian/hadoop/etc/hadoop"
      volumes:
      - name: yarn-cfg-volume
        emptyDir: {}
      - name: hive-cfg-volume
        emptyDir: {}
      - name: tez-cfg-volume
        emptyDir: {}
      - name: slider-cfg-volume
        emptyDir: {}
