# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

yarn_nm:
  image: yarn-nm
  count: 5
  cpu: 8
  mem: 30Gi
  container_mem: 30g
  container_vcpu: 8

  log_level: INFO

service:
  name: yarn-nm-serv
