# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: dockerbarbarians

yarn_nm:
  image: yarn-nm:0.1.0
  count: 5
  cpu: 8
  mem: 30Gi
  container_mem: 30g
  container_vcpu: 8

  log_level: INFO
  log_dir: /var/log/hadoop

  hdfs_conf_dir: /opt/barbarian/hadoop/etc/hadoop

service:
  name: yarn-nm-serv
