apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "fullname" . }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: {{ template "fullname" . }}
