apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ignite.fullname" . }}
  labels:
    app: {{ template "ignite.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-s3-bucket: {{ .Values.ignite.aws_s3_bucket | quote }}
  access-key: {{ .Values.ignite.aws_access_key_id | quote }}
  secret-key: {{ .Values.ignite.aws_secret_access_key | quote }}
