dependencies:
  - name: zookeeper
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: ignite
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: yarn_rm
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 4.x.x
    condition: hive_hms.db_auto
