# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

hive_hms:
  image: hive
  count: 2
  ps_mem: 8g
  mem: 8Gi

  # set db_auto: true if you want Helm to automatically install a mariadb
  # for hive metastore persistent backend 
  db_auto: false

  # specify the type of database for your hive metastore persistent backend.
  # Barbarian supports the following values here: postgres, mssql or mysql.
  # If you want to use MariaDB, then you should specify "mysql".
  db_type: mysql

  # specify the jdbc uri for your hive metastore persistent backend.
  # Barbarian supports postgresql, mariadb or mysql
  db_uri: YOUR_DB_URI

  # specify the username for your hive metastore persistent backend.
  db_username: barbarian

  # specify the password for your hive metastore persistent backend.
  # if db_auto is true then you should set the password for mariadb instead.
  db_password: "YOUR_DB_PASSWORD"

  log_level: INFO

service:
  name: hms-serv

# A bitnami mariadb can optionally be deployed by Helm for testing purposes.
# For production deployments a dedicated external database is recommended.
# Barbarians supports connection to postgres, mssql, mariadb and mysql.
mariadb:
  replication:
    enabled: false
  db:
    name: hive_metastore
    user: barbarian_hive

    #If the password is not specified, mariadb will generate a random password
    #password:

  #rootUser:
    #password:

  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi

