# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: dockerbarbarians

ignite:
  image: ignite:0.1.0
  count: 3
  cpu: 2
  mem: 8Gi
  ps_mem: 7g

  # currently only supports s3a. support for adls, google cloud storage and ceph 
  # will follow
  secondary_fs_uri: s3a://YOUR_BUCKET/
  hadoop_conf_dir: /opt/hadoop/etc/hadoop
  log_level: INFO

  s3a:
    access_key_id: YOUR_ACCESS_KEY_ID
    secret_access_key: YOUR_SECRET_ACCESS_KEY
    endpoint: s3-eu-west-1.amazonaws.com
    ssl_enabled: true
    s3guard_ddb:
      create: true
      region: eu-west-1
      capacity:
        read: 3
        write: 3

service:
  name: ignite-serv
