# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

ignite:
  image: ignite
  count: 3
  cpu: 2
  mem: 8Gi
  ps_mem: 7g

  aws_s3_bucket: YOUR_BUCKET
  aws_access_key_id: YOUR_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_SECRET_ACCESS_KEY

  log_level: INFO

service:
  name: ignite-serv
