dependencies:
  - name: zookeeper
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: yarn_rm
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: ignite
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
  - name: hive_hms
    repository: http://charts.barbarians.io/barbarian
    version: 0.1.0-badh0.1.0
