apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "fullname" . }}
spec:
  ports:
  - port: 9083
    name: server
  selector:
    app: {{ template "fullname" . }}
