# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

hive_hms:
  image: hive
  count: 3
  ps_mem: 8g
  mem: 8Gi

  # set db_auto: true if you want Helm to automatically install a mariadb
  # for hive metastore persistent backend
  db_auto: false

  # specify the jdbc uri for your hive metastore persistent backend.
  # Barbarian supports postgres, mssql, mariadb or mysql
  db_uri: YOUR_DB_URI

  # specify the type of database for your hive metastore persistent backend.
  # Barbarian supports the following values here: postgres, mssql or mysql.
  # If you want to use MariaDB, then you should specify "mysql".
  db_type: mysql

  # specify the username for your hive metastore persistent backend.
  db_username: barbarian

  # specify the password for your hive metastore persistent backend.
  # if db_auto is true then you should set the password for mariadb instead.
  db_password: "YOUR_DB_PASSWORD"

  log_level: INFO
  service:
    name: hms-serv

hive_hs2:
  image: hive
  count: 1
  llapd_count: 4
  ps_mem: 8g
  mem: 8Gi
  llapd_mem: 24g
  log_level: INFO
  service:
    name: hs2-serv

yarn_rm:
  image: yarn-rm
  count: 1
  cpu: 1
  mem: 4Gi

  log_level: INFO
  service:
    name: yarn-rm-serv

yarn_nm:
  image: yarn-nm
  count: 5
  cpu: 8
  mem: 30Gi
  container_mem: 30g
  container_vcpu: 8

  log_level: INFO

zookeeper:
  image: zookeeper
  count: 5
  cpu: 0.5
  mem: 2Gi
  ps_mem: 1g

  log_level: INFO
  service:
    name: zk-serv

ignite:
  image: ignite
  count: 5
  cpu: 2
  mem: 8Gi
  ps_mem: 7g

  aws_s3_bucket: YOUR_BUCKET
  aws_access_key_id: YOUR_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_SECRET_ACCESS_KEY

  log_level: INFO
  service:
    name: ignite-serv

# A bitnami mariadb can optionally be deployed by Helm for testing purposes.
# For production deployments a dedicated external database is recommended.
# Barbarians supports connection to postgres, mssql, mariadb and mysql.
mariadb:
  replication:
    enabled: false
  db:
    name: hive_metastore
    user: barbarian_hive

    #If the password is not specified, mariadb will generate a random password
    #password:

  #rootUser:
    #password:

  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
