# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  repo: YOUR_REPO

hive-hms:
  image: hive
  count: 3
  ps_mem: 8g
  mem: 8Gi
    
  hms_db_uri: YOUR_JDBC_URI
  hms_db_username: YOUR_JDBC_USERNAME
  hms_db_password: YOUR_JDBC_PASSWORD

  log_level: INFO
  service:
    name: hms-serv

hive-hs2:
  image: hive
  count: 1
  llapd_count: 4
  ps_mem: 8g
  mem: 8Gi
  llapd_mem: 24g
  log_level: INFO
  service:
    name: hs2-serv

yarn-rm:
  image: yarn-rm
  count: 1
  cpu: 1
  mem: 4Gi

  log_level: INFO
  service:
    name: yarn-rm-serv

yarn-nm:
  image: yarn-nm
  count: 5
  cpu: 8
  mem: 30Gi
  container_mem: 30g
  container_vcpu: 8

  log_level: INFO

zookeeper:
  image: zookeeper
  count: 5
  cpu: 0.5
  mem: 2Gi
  ps_mem: 1g

  log_level: INFO
  service:
    name: zk-serv

ignite:
  image: ignite
  count: 5
  cpu: 2
  mem: 8Gi
  ps_mem: 7g

  aws_s3_bucket: YOUR_BUCKET
  aws_access_key_id: YOUR_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_SECRET_ACCESS_KEY

  log_level: INFO
  service:
    name: ignite-serv
